project_id = "pekekgjysecbwznrvojp"

[functions.tenant-signup]
verify_jwt = false

[functions.bkash-callback]
verify_jwt = false

[functions.eps-callback]
verify_jwt = false

[functions.sitemap]
verify_jwt = false