project_id = "pekekgjysecbwznrvojp"

[functions.tenant-signup]
verify_jwt = false

[functions.bkash-callback]
verify_jwt = false

[functions.eps-callback]
verify_jwt = false

[functions.pathao-webhook]
verify_jwt = false

[functions.steadfast-webhook]
verify_jwt = false

[functions.store-bkash-callback]
verify_jwt = false

[functions.store-sslcommerz-callback]
verify_jwt = false

[functions.store-payment-init]
verify_jwt = false